cloudProvider: "aws"
distribution: "eks"
splunkObservability:
  realm: ""
  accessToken: ""
  tracesEnabled: true
  metricsEnabled: false
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: false
  profilingEnabled: false
agent:
  enabled: false
clusterReceiver:
  enabled: false
gateway:
  enabled: true
  extraEnvs:
  - name: AWS_ACCESS_KEY_ID
    value: "< YOUR AWS ACCESS KEY KEY >"
  - name: AWS_SECRET_ACCESS_KEY
    value: "< YOUR AWS SECRET ACCESS KEY >"
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  config:
    processors:
      attributes/helloworld:
        actions:
        - key: helloworld
          value: hellos3
          action: insert
    exporters:
      awss3:
        s3uploader:
            region: "ap-southeast-1"
            s3_bucket: "< YOUR BUCKET NAME >"
            s3_prefix: "trace"
            s3_partition: "minute"
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - k8sattributes
          - resourcedetection/k8s_cluster_name
          - attributes/helloworld
          - batch
          exporters:
          - awss3
          - sapm
