cloudProvider: "aws"
distribution: "eks"
splunkObservability:
  realm: ""
  accessToken: ""
  tracesEnabled: true
  metricsEnabled: false
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: false
  profilingEnabled: false
agent:
  enabled: false
clusterReceiver:
  enabled: false
gateway:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
  config:
    processors:
      attributes/helloworld:
        actions:
        - key: helloworld
          value: hellojek
          action: insert
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - k8sattributes
          - resourcedetection/k8s_cluster_name
          - attributes/helloworld
          - batch
          exporters:
          - sapm
