cloudProvider: "azure"
distribution: "aks"
clusterName: "jek-aks-v2"
splunkObservability:
  realm: "< your realm >"
  accessToken: "< your access token >"
  tracesEnabled: true
  metricsEnabled: true
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: true
  profilingEnabled: false
clusterReceiver:
  enabled: true
  config:      
    exporters:
      otlp:
        endpoint: http://XXX.XXX.XXX.XXX:4317
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          exporters:
          - otlp
agent:
  enabled: true
  config:      
    exporters:
      otlp:
        endpoint: http://XXX.XXX.XXX.XXX:4317
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          exporters:
          - otlp
        metrics/agent:
          exporters:
          - otlp
        traces:
          exporters:
          - otlp