apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mmodestino-mario
  name: mmodestino-mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmodestino-mario
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mmodestino-mario
    spec:
      containers:
      - image: pengbai/docker-supermario
        name: docker-supermario
        ports:
        - containerPort: 8080  
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/tomcat/logs
          name: var-log-mario 
      volumes:
      - name: var-log-mario
        emptyDir:
          sizeLimit: 500Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mmodestino-mario
spec:
  type: NodePort
  selector:
    app: mmodestino-mario
  ports:
    - port: 8080 
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
