apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojekv1-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellojekv1
  template:
    metadata:
      labels:
        app: hellojekv1
    spec:
      containers:
      - name: hellojekv1
        image: jchoo/hellojekv1-tomcat
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hellojekv1-tomcat-service
spec:
  selector:
    app: hellojekv1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

