version: '3.8'

services:
  otelcol:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: otelcol
    environment:
      - SPLUNK_ACCESS_TOKEN=< your access token >
      - SPLUNK_REALM=< your realm >
      - SPLUNK_CONFIG=/etc/collector.yaml
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
    volumes:
      - ./jek-collector-v1.yaml:/etc/collector.yaml:ro
    restart: always
