apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
      - name: microservice-a-container
        image: jchoo/microservice-chain-a:v1.0.0
        env:
        - name: TARGET_SERVICE_URL
          value: http://microservice-b-service.default.svc.cluster.local/b
        resources:
          limits:
            memory: "1Gi" 
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a-service
spec:
  selector:
    app: microservice-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
      - name: microservice-b-container
        image: jchoo/microservice-chain-b:v1.0.0
        env:
        - name: TARGET_SERVICE_URL
          value: http://microservice-c-service.default.svc.cluster.local/c
        resources:
          limits:
            memory: "1Gi" 
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b-service
spec:
  selector:
    app: microservice-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-c
  template:
    metadata:
      labels:
        app: microservice-c
    spec:
      containers:
      - name: microservice-c-container
        image: jchoo/microservice-chain-c:v1.0.0
        env:
        - name: TARGET_SERVICE_URL
          value: http://microservice-d-service.default.svc.cluster.local/d
        resources:
          limits:
            memory: "1Gi" 
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-c-service
spec:
  selector:
    app: microservice-c
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-d
  template:
    metadata:
      labels:
        app: microservice-d
    spec:
      containers:
      - name: microservice-d-container
        image: jchoo/microservice-chain-d:v1.0.0
        resources:
          limits:
            memory: "1Gi" 
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-d-service
spec:
  selector:
    app: microservice-d
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3004