certmanager:
  enabled: true
operator:
  enabled: true
cloudProvider: aws
clusterName: jek-eks-ec2-otel-operator
distribution: eks
environment: jek-sandbox
gateway:
  enabled: false
splunkObservability:
  accessToken: <your o11y access token>
  profilingEnabled: true
  realm: <your realm e.g. us1>
  infrastructureMonitoringEventsEnabled: true
logsEngine: otel
splunkPlatform:
  endpoint: https://<the hec endpoint url>.com/services/collector
  token: <your hec token>
  index: <your index e.g. main>
  insecureSkipVerify: true
autodetect:
  istio: true
  prometheus: true
agent:
  enabled: true
  config:
    service:
      telemetry:
        logs:
          encoding: json
clusterReceiver:
  k8sObjects:
    - name: events
      mode: watch
      group: events.k8s.io
      namespaces: [default]