apiVersion: v1
data:
  relay: |
    exporters:
      signalfx:
        access_token: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}
        api_url: https://api.us1.signalfx.com
        disable_default_translation_rules: true
        ingest_url: https://ingest.us1.signalfx.com
        timeout: 10s
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    processors:
      batch:
        send_batch_max_size: 32768
      memory_limiter:
        check_interval: 2s
        limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
      resource:
        attributes:
        - action: insert
          key: metric_source
          value: kubernetes
        - action: upsert
          key: k8s.cluster.name
          value: jek-rosa
      resource/add_collector_k8s:
        attributes:
        - action: insert
          key: k8s.node.name
          value: ${K8S_NODE_NAME}
        - action: insert
          key: k8s.pod.name
          value: ${K8S_POD_NAME}
        - action: insert
          key: k8s.pod.uid
          value: ${K8S_POD_UID}
        - action: insert
          key: k8s.namespace.name
          value: ${K8S_NAMESPACE}
      resource/k8s_cluster:
        attributes:
        - action: insert
          key: receiver
          value: k8scluster
      resourcedetection:
        detectors:
        - env
        - system
        override: true
        timeout: 15s
    receivers:
      k8s_cluster:
        auth_type: serviceAccount
        distribution: openshift
        metadata_exporters:
        - signalfx
      prometheus/k8s_cluster_receiver:
        config:
          scrape_configs:
          - job_name: otel-k8s-cluster-receiver
            metric_relabel_configs:
            - action: drop
              regex: otelcol_rpc_.*
              source_labels:
              - __name__
            - action: drop
              regex: otelcol_http_.*
              source_labels:
              - __name__
            - action: drop
              regex: otelcol_processor_batch_.*
              source_labels:
              - __name__
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${K8S_POD_IP}:8889
    service:
      extensions:
      - health_check
      pipelines:
        metrics:
          exporters:
          - signalfx
          processors:
          - memory_limiter
          - batch
          - resource
          - resource/k8s_cluster
          receivers:
          - k8s_cluster
        metrics/collector:
          exporters:
          - signalfx
          processors:
          - memory_limiter
          - batch
          - resource/add_collector_k8s
          - resourcedetection
          - resource
          receivers:
          - prometheus/k8s_cluster_receiver
      telemetry:
        metrics:
          address: 0.0.0.0:8889
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: splunk-otel-collector
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-12-09T08:54:24Z"
  labels:
    app: splunk-otel-collector
    app.kubernetes.io/instance: splunk-otel-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-otel-collector
    app.kubernetes.io/version: 0.113.0
    chart: splunk-otel-collector-0.113.0
    helm.sh/chart: splunk-otel-collector-0.113.0
    heritage: Helm
    release: splunk-otel-collector
  name: splunk-otel-collector-otel-k8s-cluster-receiver
  namespace: default
  resourceVersion: "77143"
  uid: a141bfa5-44e6-49d3-8f8e-5caf3de37d6c
