apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do cat /app/hello.txt; sleep 10; done"]
    resources:
      limits:
        memory: "1Gi" 
        cpu: "0.5"
    volumeMounts:
    - name: host-volume
      mountPath: /app
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: <your-node-name>