apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do ls -l /app/splunk-otel-javaagent.jar; sleep 10; done"]
    resources:
      limits:
        memory: "2Gi" 
        cpu: "1"
    volumeMounts:
    - name: host-volume
      mountPath: /opt/otel
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: <YOUR NODE NAME FROM KUBECTLE GET NODES -O WIDE>