apiVersion: v1
kind: Pod
metadata:
  name: jar-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh"]
    args: ['-c', 'ls -l /app/splunk-otel-javaagent.jar && echo "JAR found!"']
    resources:
      limits:
        memory: "1Gi" 
        cpu: "0.5"
    volumeMounts:
    - name: host-volume
      mountPath: /app
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: <your-node-name>