apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  region: ap-southeast-1
  version: "1.30"
  name: "jek-eks-ec2-16dec2024"

managedNodeGroups:
- name: jek-eks-ec2-managednodegroup-workers
  instanceType: m5.2xlarge
  volumeSize: 50
  desiredCapacity: 3
  # ssh:
  #   publicKeyPath: ~/.ssh/id_rsa.pub

# secretsEncryption:
#   keyARN: <YOUR-KMS-KEY-ARN>
 
# managedNodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 1
#     ssh: # import public key from file
#       publicKeyPath: ~/.ssh/id_rsa_tests.pub
#   - name: ng-2
#     instanceType: m5.large
#     desiredCapacity: 1
#     ssh: # use existing EC2 key
#       publicKeyName: ec2_dev_key
#   - name: ng-3
#     instanceType: m5.large
#     desiredCapacity: 1
#     ssh: # import inline public key
#       publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqZEdzvHnK/GVP8nLngRHu/GDi/3PeES7+Bx6l3koXn/Oi/UmM9/jcW5XGziZ/oe1cPJ777eZV7muEvXg5ZMQBrYxUtYCdvd8Rt6DIoSqDLsIPqbuuNlQoBHq/PU2IjpWnp/wrJQXMk94IIrGjY8QHfCnpuMENCucVaifgAhwyeyuO5KiqUmD8E0RmcsotHKBV9X8H5eqLXd8zMQaPl+Ub7j5PG+9KftQu0F/QhdFvpSLsHaxvBzA5nhIltjkaFcwGQnD1rpCM3+UnQE7Izoa5Yt1xoUWRwnF+L2TKovW7+bYQ1kxsuuiX149jXTCJDVjkYCqi7HkrXYqcC1sbsror someuser@hostname"
#   - name: ng-4
#     instanceType: m5.large
#     desiredCapacity: 1
#     ssh: # enable SSH using SSM
#       enableSsm: true

# managedNodeGroups:
#   - name: jek-eks-ec2-ng-1-workers
#     labels: { role: workers }
#     instanceType: m5.4xlarge
#     desiredCapacity: 2
#     volumeSize: 50
#   - name: jek-eks-ec2-ng-2-builders
#     labels: { role: builders }
#     instanceType: m5.4xlarge
#     desiredCapacity: 1
#     volumeSize: 55
#     privateNetworking: true
