apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jek-eks-ec2-cluster-<add a date>
  region: ap-southeast-1
  version: "1.28"

managedNodeGroups:
- name: jek-eks-ec2-managednodegroup-workers
  instanceType: m5.2xlarge
  desiredCapacity: 3
 
# managedNodeGroups:
#   - name: jek-eks-ec2-ng-1-workers
#     labels: { role: workers }
#     instanceType: m5.4xlarge
#     desiredCapacity: 2
#     volumeSize: 50
#   - name: jek-eks-ec2-ng-2-builders
#     labels: { role: builders }
#     instanceType: m5.4xlarge
#     desiredCapacity: 1
#     volumeSize: 55
#     privateNetworking: true
