apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: splunk-monitoring
  name: otel-collector-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
