apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-collector-rolebinding
  namespace: splunk-monitoring
subjects:
- kind: ServiceAccount
  name: traceid-load-balancing-gateway-otel-collector
  namespace: splunk-monitoring
roleRef:
  kind: Role
  name: otel-collector-role
  apiGroup: rbac.authorization.k8s.io
