cloudProvider: "aws"
distribution: "eks"
splunkObservability:
  realm: ""
  accessToken: ""
  tracesEnabled: true
  metricsEnabled: false
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: false
  profilingEnabled: false
agent:
  enabled: false
clusterReceiver:
  enabled: false
gateway:
  enabled: true
  replicaCount: 3
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  config:
    processors:
      attributes/helloworld:
        actions:
        - key: tailgw
          value: hello-world-v2
          action: upsert
        - key: jek2
          value: jek-tailgw-v2
          action: insert
      tail_sampling:
        policies:
          [ 
            # {
            #   name: errors-policy,
            #   type: status_code,
            #   status_code: {status_codes: [ERROR]}
            # },
            # {
            #   name: randomized-policy,
            #   type: probabilistic,
            #   probabilistic: {sampling_percentage: 50}
            # },         
            {
              name: probabilistic-policy-for-error,
              type: and,
              and: {
                and_sub_policy: 
                [
                  {
                    name: error-policy,
                    type: status_code,
                    status_code: {status_codes: [ERROR]}
                  },
                  {
                    name: probabilistic-policy,
                    type: probabilistic,
                    probabilistic: {sampling_percentage: 50}
                  },
                ]
              }
            },
            {
              name: probabilistic-policy-for-non-error,
              type: probabilistic,
              probabilistic: {sampling_percentage: 20}
            },
          ]
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - k8sattributes
          - resourcedetection/k8s_cluster_name
          - attributes/helloworld
          - tail_sampling
          - batch
          exporters:
          - sapm
