cloudProvider: "aws"
distribution: "eks"
splunkObservability:
  realm: ""
  accessToken: ""
  tracesEnabled: true
  metricsEnabled: false
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: false
  profilingEnabled: false
agent:
  enabled: false
clusterReceiver:
  enabled: false
gateway:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  config:
    processors:
      attributes/helloworld:
        actions:
        - key: tracegw
          value: hello-world-v4
          action: upsert
        - key: jek
          value: jek-tracegw-v4
          action: insert
    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          k8s:
            service: tail-sampling-gateway-splunk-otel-collector.splunk-monitoring
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          - zipkin
          processors:
          - memory_limiter
          - attributes/helloworld
          - batch
          exporters:
          - loadbalancing