cloudProvider: "aws"
distribution: "eks"
splunkObservability:
  realm: ""
  accessToken: ""
  tracesEnabled: true
  metricsEnabled: false
  logsEnabled: false
  infrastructureMonitoringEventsEnabled: false
  profilingEnabled: false
agent:
  enabled: false
clusterReceiver:
  enabled: false
gateway:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  # config:
  #   exporters:
  #     loadbalancing:
  #       protocol:
  #         otlp:
  #           timeout: 1s
  #           tls:
  #             insecure: true
  #       resolver:
  #         k8s:
  #           service: tail-sampling-gateway-splunk-otel-collector.splunk-monitoring
  #           ports:
  #             - 4317
  #   service:
  #     pipelines:
  #       traces:
  #         exporters: [loadbalancing]