apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-maven-k8s-eks-fargate
  labels:
    app: javaspringmaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspringmaven
  template:
    metadata:
      labels:
        app: javaspringmaven
    spec:
      containers:
      - name: jekspringwebapp
        image: jekbao/jekspringwebapp:v1
        ports:
        - containerPort: 8080
        env:
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: deployment.environment=jek-sandbox
          - name: OTEL_SERVICE_NAME
            value: jek-spring-maven-k8s-eks-fargate-http
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: splunk-otel-collector-1646814262.default.svc:4317
