clusterName: "jek-v6-cluster"
logsEngine: otel
cloudProvider: "azure"
distribution: "aks"
splunkPlatform:
  endpoint: "https://< your instance id >.splunk.show:8088/services/collector"
  token: "< your hec token >"
  index: "otel_events"
  insecureSkipVerify: true
logsCollection:
  containers: 
    containerRuntime: "containerd"
    excludeAgentLogs: true
  extraFileLogs:
    filelog/jek-log-volume-v6:
      include: 
      - /tmp/jekazurecsiv6/*/volumes/kubernetes.io~csi/azure-file-pv/mount/log*.log
      start_at: beginning
      storage: file_storage
      include_file_path: true
      include_file_name: false
      resource:
        com.splunk.index: otel_events
        com.splunk.source: /var/log/emptydir/jek-log-volume-v6
        host.name: 'EXPR(env("K8S_NODE_NAME"))'
        com.splunk.sourcetype: kube:jek-log-volume-v6
      operators:
      - parse_from: attributes["log.file.path"]
        regex: ^\/tmp\/jekazurecsiv6\/(?P<jek_pod_uid>[^\/]+)\/volumes\/kubernetes\.io\~csi\/(?P<jek_volume_name>[^\/]+)\/.+$
        type: regex_parser
      - from: attributes.jek_pod_uid
        to: resource["k8s.pod.uid"]
        type: move
      - from: attributes.jek_volume_name
        to: resource["k8s.volume.name"]
        type: copy
agent:
  extraVolumes:
  - name: jekvolumev6
    hostPath:
      path: /var/lib/kubelet/pods/
  extraVolumeMounts: 
  - name: jekvolumev6
    mountPath: /tmp/jekazurecsiv6
    readOnly: true
  config:
    service:
      pipelines:
        logs/host:
          exporters:
          - splunk_hec/platform_logs
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resource
          receivers:
          - filelog/jek-log-volume-v6