apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-maven-k8s-eks-ec2
  labels:
    app: javaspringmaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspringmaven
  template:
    metadata:
      labels:
        app: javaspringmaven
    spec:
      containers:
      - name: jekspringwebapp
        image: jekbao/jekspringwebapp:v2
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-maven-k8s-eks-ec2-with-annotation
  labels:
    app: javaspringmavenwithannotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspringmavenwithannotation
  template:
    metadata:
      labels:
        app: javaspringmavenwithannotation
      annotations:
        otel.splunk.com/inject-java: "true"
    spec:
      containers:
      - name: jekspringwebappwithannotation
        image: jekbao/jekspringwebapp:v2
        ports:
        - containerPort: 8080