clusterName: "< your cluster name >"
logsEngine: otel
cloudProvider: "azure"
distribution: "aks"
splunkPlatform:
  endpoint: "https://< your instance id >.splunk.show:8088/services/collector"
  token: "< your hec token >"
  index: "otel_events"
  metricsIndex: "otel_metrics"
  insecureSkipVerify: true
  metricsEnabled: true
logsCollection:
  containers: 
    containerRuntime: "containerd"
    excludeAgentLogs: false